# Generated by Django 5.0.4 on 2024-05-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_post_thubnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thubnail',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='base.tags'),
        ),
    ]
